name: Build
on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: Compile
      run: make release
      env:
        ARCHIVE: 1
    - uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: build/*.zip
  windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        release: false
        install: git zip make mingw-w64-x86_64-gcc
    - name: Compile
      shell: msys2 {0}
      run: make release
      env:
        ARCHIVE: 1
    - uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: build/*.zip
  macos:
    name: macOS
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make release
      env:
        ARCHIVE: 1
    - uses: actions/upload-artifact@v2
      with:
        name: macOS
        path: build/*.zip
